fix: property console is not registered
koishijs/koishi-plugin-downloads pull request #3
Opened 2023-11-04 10:48 UTC by idanran

fixes #2

2023-11-04 18:41 UTC, shigma requested changes
这么写仍然会报错。应该把 inject 删掉，下面两处调用改成

```ts
this.ctx.get('console.downloads')?.refresh()
```

2023-11-05 04:32 UTC, idanran commented
> 这么写仍然会报错。应该把 inject 删掉，下面两处调用改成形如
> 
> ```ts
> this.ctx.get('console.downloads')?.refresh()
> ```

嗯嗯

2023-11-05 05:42 UTC, shigma requested changes

2023-11-05 05:42 UTC, shigma commented on src/service.ts
>      if (this.ctx.console?.downloads) {
if 不需要

2023-11-05 05:47 UTC, idanran commented on src/service.ts
>      if (this.ctx.console?.downloads) {
> if 不需要

好

2023-11-05 05:50 UTC, shigma approved these changes

2023-11-05 06:16 UTC, merged